<a href="https://colab.research.google.com/github/Sereenamariyam/Python_assignment/blob/main/numpy_and_pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.arange(10, 50)
reshaped = arr.reshape(4, 10)
last_col = reshaped[:, -1]

print("Reshaped Array:\n", reshaped)
print("Last Column:", last_col)


Reshaped Array:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last Column: [19 29 39 49]


In [2]:
mat1 = np.full((3, 3), 5)
mat2 = np.arange(1, 10).reshape(3, 3)

add = mat1 + mat2
multiply = mat1 * mat2
transpose_result = multiply.T

print("Addition:\n", add)
print("Element-wise Multiplication:\n", multiply)
print("Transpose:\n", transpose_result)


Addition:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Element-wise Multiplication:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
arr = np.random.randint(10, 100, 15)
replaced_arr = np.where(arr > 50, -1, arr)
count_replaced = np.sum(arr > 50)

print("Original:", arr)
print("Modified:", replaced_arr)
print("Count Replaced:", count_replaced)


Original: [71 73 29 22 19 64 39 81 97 49 47 32 72 96 35]
Modified: [-1 -1 29 22 19 -1 39 -1 -1 49 47 32 -1 -1 35]
Count Replaced: 7


In [4]:
arr = np.random.rand(5, 4)
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)

# Normalize each row: x_normalized = (x - min) / (max - min)
normalized = (arr - arr.min(axis=1, keepdims=True)) / (arr.max(axis=1, keepdims=True) - arr.min(axis=1, keepdims=True))

print("Original Array:\n", arr)
print("Row with max sum:", max_row_index)
print("Normalized Array:\n", normalized)


Original Array:
 [[0.43484331 0.70374436 0.61935461 0.06351929]
 [0.65063434 0.43975431 0.84616347 0.51335999]
 [0.12333237 0.32225576 0.8737192  0.65866134]
 [0.63745533 0.61081513 0.26965985 0.08541547]
 [0.60697481 0.09933164 0.48413364 0.78886556]]
Row with max sum: 1
Normalized Array:
 [[0.57998982 1.         0.86818737 0.        ]
 [0.51888603 0.         1.         0.18111227]
 [0.         0.26509446 1.         0.71340401]
 [1.         0.95174227 0.33375194 0.        ]
 [0.73621204 0.         0.55806101 1.        ]]


In [5]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique = np.unique(arr)
duplicates = np.array([x for x in unique if np.count_nonzero(arr == x) > 1])

print("Unique elements:", unique)
print("Duplicates:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicates: [1 3 5]


In [6]:
arr = np.arange(1, 37).reshape(6, 6)
submatrix = arr[1:5, 1:5]
even_numbers = submatrix[submatrix % 2 == 0]

print("4x4 Middle Submatrix:\n", submatrix)
print("Even Numbers in Submatrix:", even_numbers)


4x4 Middle Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even Numbers in Submatrix: [ 8 10 14 16 20 22 26 28]


In [7]:
arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
converted = flattened.reshape(4, 3)

print("Original:\n", arr)
print("Reshaped to (2,6):\n", reshaped)
print("Flattened:", flattened)
print("Reshaped to (4,3):\n", converted)


Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])  # Append row

# Append column
new_col = np.array([[7], [8], [9]])
a = np.hstack([a, new_col])

print("Final Array:\n", a)


Final Array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c])
reshaped = joined.reshape(3, 3)
diagonal = np.diag(reshaped)

print("Joined and Reshaped:\n", reshaped)
print("Diagonal Elements:", diagonal)


Joined and Reshaped:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Elements: [1 5 9]


In [10]:
arr = np.arange(1, 21)
filtered = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = filtered.size

print("Divisible by 3 or 5:", filtered)
print("Count:", count)


Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9


Pandas

In [15]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [16]:
print(df.head(10))


   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

In [17]:
print(df.isnull().sum())


survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [18]:
survival_rate = df.groupby('sex')['survived'].mean() * 100
print(survival_rate)


sex
female    74.203822
male      18.890815
Name: survived, dtype: float64


In [19]:
avg_age = df['age'].mean()
median_age = df['age'].median()
std_age = df['age'].std()

print(f"Average Age: {avg_age:.2f}")
print(f"Median Age: {median_age}")
print(f"Standard Deviation: {std_age:.2f}")


Average Age: 29.70
Median Age: 28.0
Standard Deviation: 14.53


In [20]:
print(df['pclass'].value_counts())


pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [21]:
filtered = df[(df['sex'] == 'female') & (df['age'] < 18) & (df['survived'] == 1)]
print(filtered)


     survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  femal

In [22]:
median_age = df['age'].median()
df['age'].fillna(median_age, inplace=True)


/tmp/ipython-input-22-528900305.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(median_age, inplace=True)


In [34]:
def classify_age(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(classify_age)


In [28]:
top_fares = df.sort_values(by='fare', ascending=False).head(5)
print(top_fares[['fare']])

         fare
679  512.3292
258  512.3292
737  512.3292
88   263.0000
438  263.0000


In [29]:
avg_fare = df.groupby(['pclass', 'sex'])['fare'].mean()
print(avg_fare)


pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


In [30]:
df.rename(columns={'sex': 'gender', 'fare': 'ticket_fare'}, inplace=True)


In [31]:
survival_by_class = df.groupby(['pclass', 'survived']).size()
print(survival_by_class)


pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64


In [32]:
avg_age_grouped = df.groupby(['pclass', 'gender'])['age'].mean()
print(avg_age_grouped)


pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64
